spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${GSV_USERNAME}
    password: ${GSV_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: ${CLOUDAMQP_URL}
    virtual-host: ${CLOUDAMQP_VHOST}
    password: ${CLOUDAMQP_PASSWORD}
    port: ${CLOUDAMQP_PORT}
