spring:
  profiles:
    active: @spring.profiles.active@

queue:
  name: resultados
  exchange: Resultados

application:
  feign:
    url-users: https://user-info.herokuapp.com/users

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    path: /api
